BASE:
- ''
DATA:
  BATCH_SIZE: 24
  IMG_SIZE: 224
MODEL:
  DROP_PATH_RATE: 0.2
  DROP_RATE: 0.0
  NAME: swin_tiny_patch4_window7_224
  NUM_CLASSES: 2
  PRETRAIN_CKPT: ../configs/swin_tiny_patch4_window7_224.pth
  SWIN:
    APE: false
    DECODER_DEPTHS:
    - 2
    - 2
    - 2
    - 1
    DEPTHS:
    - 2
    - 2
    - 2
    - 2
    EMBED_DIM: 96
    FINAL_UPSAMPLE: expand_first
    IN_CHANS: 3
    MLP_RATIO: 4.0
    NUM_HEADS:
    - 3
    - 6
    - 12
    - 24
    PATCH_NORM: true
    PATCH_SIZE: 4
    QKV_BIAS: true
    QK_SCALE: null
    WINDOW_SIZE: 7
  TYPE: swin
TRAIN:
  BASE_LR: 0.0003
  EPOCHS: 100
  LR_SCHEDULER:
    DECAY_EPOCHS: 10
    DECAY_RATE: 0.5
    NAME: cosine
  NUM_GPUS: 1
  OPTIMIZER:
    BETAS:
    - 0.9
    - 0.999
    EPS: 1.0e-07
    MOMENTUM: 0.9
    NAME: adamw
  START_EPOCH: 0
  USE_CHECKPOINT: false
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.0001
